-- @author  (Fernando A. Vazquez M.)
-- @version (v1.0.0)

DROP DATABASE IF EXISTS APP_ASISTENCIAS;

CREATE DATABASE IF NOT EXISTS APP_ASISTENCIAS;

USE APP_ASISTENCIAS;

DROP TABLE IF EXISTS EMPRESAS;

CREATE TABLE IF NOT EXISTS EMPRESAS (
    ID_EMPRESA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_EMPRESAS PRIMARY KEY (ID_EMPRESA),
    NOMBRE VARCHAR(30) NOT NULL,
    TELEFONO VARCHAR(13) NULL
);

DROP TABLE IF EXISTS SUCURSALES;

CREATE TABLE IF NOT EXISTS SUCURSALES (
    ID_SUCURSAL INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_SUCURSALES PRIMARY KEY (ID_SUCURSAL),
    ID_EMPRESA INT NOT NULL,
    CONSTRAINT FK_SUCURSALES_TO_EMPRESAS FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESAS (ID_EMPRESA),
    NOMBRE VARCHAR(20) NULL,
    DIRECCION VARCHAR(120) NULL
);

DROP TABLE IF EXISTS CATEGORIAS_TURNOS;

CREATE TABLE IF NOT EXISTS CATEGORIAS_TURNOS (
    ID_CATEGORIA_TURNO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CATEGORIAS_TURNOS PRIMARY KEY (ID_CATEGORIA_TURNO),
    NOMBRE VARCHAR(15) NULL,
    HORA_INICIAL TIME NULL,
    HORA_FINAL TIME NULL
);

DROP TABLE IF EXISTS CATEGORIAS_ASISTENCIAS;

CREATE TABLE IF NOT EXISTS CATEGORIAS_ASISTENCIAS (
    ID_CATEGORIA_ASISTENCIA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_CATEGORIAS_ASISTENCIAS PRIMARY KEY (ID_CATEGORIA_ASISTENCIA),
    NOMBRE VARCHAR(10) NOT NULL DEFAULT 'FALTA'
);

DROP TABLE IF EXISTS TURNOS;

CREATE TABLE IF NOT EXISTS TURNOS (
    ID_TURNO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_TURNOS PRIMARY KEY (ID_TURNO),
    ID_SUCURSAL INT NOT NULL,
    CONSTRAINT FK_TURNOS_TO_SUCURSALES FOREIGN KEY (ID_SUCURSAL) REFERENCES SUCURSALES (ID_SUCURSAL),
    ID_CATEGORIA_TURNO INT NOT NULL,
    CONSTRAINT FK_TURNOS_TO_CATEGORIAS_TURNOS FOREIGN KEY (ID_CATEGORIA_TURNO) REFERENCES CATEGORIAS_TURNOS (ID_CATEGORIA_TURNO),
    DIA DATE NULL -- EJEMPLO (2025-03-11)
);

DROP TABLE IF EXISTS ROLES_EMPLEADOS;

CREATE TABLE IF NOT EXISTS ROLES_EMPLEADOS (
    ID_ROL_EMPLEADO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ROLES_EMPLEADOS PRIMARY KEY (ID_ROL_EMPLEADO),
    NOMBRE VARCHAR(8) NOT NULL DEFAULT 'EMPLEADO'
);

DROP TABLE IF EXISTS EMPLEADOS;

CREATE TABLE IF NOT EXISTS EMPLEADOS (
    ID_EMPLEADO INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
    ID_ROL_EMPLEADO INT NULL,
    CONSTRAINT FK_EMPLEADOS_TO_ROLES_EMPLEADOS FOREIGN KEY (ID_ROL_EMPLEADO) REFERENCES ROLES_EMPLEADOS (ID_ROL_EMPLEADO),
    NOMBRES VARCHAR(30) NULL,
    APELLIDOS VARCHAR(30) NULL,
    EMAIL VARCHAR(50) NULL,
    HASHED_PASSWORD VARCHAR(255) NULL,
    TELEFONO VARCHAR(12) NULL,
    USUARIO VARCHAR(25) NULL
);

DROP TABLE IF EXISTS TURNOS_has_EMPLEADOS;

CREATE TABLE IF NOT EXISTS TURNOS_has_EMPLEADOS (
    ID_TURNOS_HAS_EMPLEADOS INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_TURNOS_HAS_EMPLEADOS PRIMARY KEY (ID_TURNOS_HAS_EMPLEADOS),
    ID_TURNO INT NOT NULL,
    CONSTRAINT TURNOS_HAS_EMPLEADOS_TO_TURNOS FOREIGN KEY (ID_TURNO) REFERENCES TURNOS (ID_TURNO),
    ID_EMPLEADO INT NOT NULL,
    CONSTRAINT TURNOS_HAS_EMPLEADOS_TO_EMPLEADOS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO)
);

DROP TABLE IF EXISTS ASISTENCIAS;

CREATE TABLE IF NOT EXISTS ASISTENCIAS (
    ID_ASISTENCIA INT AUTO_INCREMENT NOT NULL,
    CONSTRAINT PK_ASISTENCIAS PRIMARY KEY (ID_ASISTENCIA),
    ID_EMPLEADO INT NOT NULL,
    CONSTRAINT FK_ASISTENCIAS_TO_EMPLEADOS FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO),
    ID_CATEGORIA_ASISTENCIA INT NOT NULL,
    CONSTRAINT FK_ASISTENCIAS_TO_CATEGORIAS_ASISTENCIAS FOREIGN KEY (ID_CATEGORIA_ASISTENCIA) REFERENCES CATEGORIAS_ASISTENCIAS (ID_CATEGORIA_ASISTENCIA),
    ID_TURNO INT NOT NULL,
    CONSTRAINT FK_ASISTENCIAS_TO_TURNOS FOREIGN KEY (ID_TURNO) REFERENCES TURNOS (ID_TURNO)
);
