--- @author  (Fernando A. Vazquez M.)
--- @version (v1.0.0)

--- INSERCION DE DATOS POR DEFECTO EN LA BASE DE DATOS

--- TABLA (EMPRESAS)
INSERT INTO EMPRESAS(NOMBRE)VALUES('Super Market ML');

--- TABLA (SUCURSALES)
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Tlaxcala','Colonia Tlaxcala, debajo de la colonia Lomas del Pedregal');
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Otilio','En blvd. Otilio Glz, en frente de escuela Adolfo L. Mateos, a lado de colonia Lomas de Zapaliname');
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Alamo','En colonia el Alamo, antes de llegar a Sabritas');
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Morelos','En colonia Ampliacion Morelos, a contraesquina del negocio de pollos EL MORRO');
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Fundadores','En colonia Loma Linda, antes de llegar a campus Lobos UAdeC');
INSERT INTO SUCURSALES(ID_EMPRESA,NOMBRE,DIRECCION)VALUES(1,'Zona Centro','Ubicada en el centro de la ciudad, al lado de calle Xicotencatl');

--- TABLA (CATEGORIAS_TURNOS)
INSERT INTO CATEGORIAS_TURNOS(NOMBRE,HORA_INICIAL,HORA_FINAL)VALUES('Primero','08:00:00','14:00:00');
INSERT INTO CATEGORIAS_TURNOS(NOMBRE,HORA_INICIAL,HORA_FINAL)VALUES('Segundo','14:05:00','20:00:00');

--- TABLA (CATEGORIAS_ASISTENCIAS)
INSERT INTO CATEGORIAS_ASISTENCIAS(NOMBRE)VALUES('Asistencia');
INSERT INTO CATEGORIAS_ASISTENCIAS(NOMBRE)VALUES('Retardo');
INSERT INTO CATEGORIAS_ASISTENCIAS(NOMBRE)VALUES('Falta');

--- TABLA (ROLES_EMPLEADOS)
INSERT INTO ROLES_EMPLEADOS(NOMBRE)VALUES('Dueño');
INSERT INTO ROLES_EMPLEADOS(NOMBRE)VALUES('RH');
INSERT INTO ROLES_EMPLEADOS(NOMBRE)VALUES('Guardia');
INSERT INTO ROLES_EMPLEADOS(NOMBRE)VALUES('Empleado');
